package com.sentinel.service

import kotlinx.coroutines.*
import kotlinx.coroutines.flow.Flow
import retrofit2.http.GET
import retrofit2.http.Path
import retrofit2.http.Query

/**
 * GitHub API service interface
 * Generated by Retrofit or implemented manually
 * 
 * Licensed under Apache 2.0 via com.sentinel.editor
 */
interface GitHubApiService {
    
    /**
     * Get repositories list for authenticated user
     */
    @GET("user/repos")
    suspend fun listRepositories(
        @Query("type") type: String = "all"
    ): List<RepositoryItem>
    
    /**
     * Get repository by ID
     */
    @GET("repos/{owner}/{repo}")
    suspend fun getRepository(
        @Path("owner") owner: String,
        @Path("repo") repo: String
    ): RepositoryInfo
    
    /**
     * List files in repository
     */
    @GET("repos/{owner}/{repo}/contents/{path}")
    suspend fun listRepositoryContents(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Path("path") path: String = "",
        @Query("recursive") recursive: Boolean = true
    ): List<RepositoryContent>
    
    /**
     * Get file content
     */
    @GET("repos/{owner}/{repo}/contents/{path}")
    suspend fun getFileContent(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Path("path") path: String
    ): FileContent
    
    /**
     * Read file from repo
     */
    @POST("repos/{owner}/{repo}/contents/{path}")
    suspend fun readFile(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Path("path") path: String,
        @Body content: String
    ): ResponseInfo
    
    /**
     * Create new file
     */
    @POST("repos/{owner}/{repo}/contents")
    suspend fun createFile(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Query("filename") filename: String,
        @Query("message") message: String? = null,
        @Body content: String
    ): ResponseInfo
    
    /**
     * Update file (edit)
     */
    @PUT("repos/{owner}/{repo}/contents/{path}")
    suspend fun updateFile(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Path("path") path: String,
        @Query("message") message: String? = null,
        @Query("branch") branch: String = "main",
        @Body content: String
    ): ResponseInfo
    
    /**
     * Delete file
     */
    @DELETE("repos/{owner}/{repo}/contents/{path}")
    suspend fun deleteFile(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Path("path") path: String,
        @Query("message") message: String? = null,
        @Query("branch") branch: String = "main"
    ): ResponseInfo
    
    /**
     * Get pull requests
     */
    @GET("repos/{owner}/{repo}/pulls")
    suspend fun listPullRequests(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Query("state") state: String = "open"
    ): List<PullRequest>
    
    /**
     * Get pull request details
     */
    @GET("repos/{owner}/{repo}/pulls/{number}")
    suspend fun getPullRequest(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Path("number") number: Int
    ): PullRequest
    
    /**
     * Create pull request
     */
    @POST("repos/{owner}/{repo}/pulls")
    suspend fun createPullRequest(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Body request: NewPullRequest
    ): PullRequest
    
    /**
     * Get commit by SHA
     */
    @GET("repos/{owner}/{repo}/commits/{commit_sha}")
    suspend fun getCommit(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Path("commit_sha") commitSha: String
    ): Commit
    
    /**
     * Get repository commit
     */
    @GET("repos/{owner}/{repo}/commits/{sha}")
    suspend fun getCommit(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Path("sha") sha: String
    ): Commit
    
    /**
     * Get list of commits
     */
    @GET("repos/{owner}/{repo}/commits")
    suspend fun listCommits(
        @Path("owner") owner: String,
        @Path("repo") repo: String,
        @Query("per_page") perPage: Int = 30
    ): List<GitCommit>
}